### ISSUE TITLE
Handle the case that ActiveMQ restarts

### ISSUE THREAD

**Issue by b-long** [Bioconductor/packagebuilder#5]
When ActiveMQ is restarted, build nodes (`server.py`) will fail immediately with : 

```
 [*] Waiting for messages. To exit press CTRL+C
 [x] Received '{"force": true, "job_id": "RTCGA.rppa_20151110165530", "repository": "scratch", "bioc_version": "3.3", "svn_url": "https://tracker.bioconductor.org/file6664/RTCGA.rppa_0.99.1.tar.gz", "r_version": "3.3", "client_id": "single_package_builder_autobuild:1335:RTCGA.rppa_0.99.1.tar.gz", "time": "Tue Nov 10 2015 16:55:30 GMT-0800 (PST)"}'
Wrote job info to /Users/pkgbuild/packagebuilder/jobs/RTCGA.rppa_20151110165530/manifest.json.
shell_cmd = /Users/pkgbuild/packagebuilder/morelia.sh
Receipt: morelia-319612
Traceback (most recent call last):
  File "server.py", line 129, in <module>
    frame = stomp.receive_frame()
  File "build/bdist.macosx-10.9-intel/egg/stompy/stomp.py", line 214, in receive_frame
  File "build/bdist.macosx-10.9-intel/egg/stompy/frame.py", line 160, in get_message
  File "build/bdist.macosx-10.9-intel/egg/stompy/frame.py", line 49, in get
  File "build/bdist.macosx-10.9-intel/egg/stompy/frame.py", line 200, in parse_frame
  File "build/bdist.macosx-10.9-intel/egg/stompy/frame.py", line 270, in _getline
stompy.frame.UnknownBrokerResponseError: empty reply

```

**Comment by mtmorgan** [comment]
seems like the builders can have a [failover transport](http://activemq.apache.org/failover-transport-reference.html) and try harder to stay / re-connect.

**Comment by b-long** [comment]
:+1: Nice find @mtmorgan .  That may be exactly what we need :smile:

**Comment by lshep** [comment]
Closing - Migrated from ActiveMQ to rabbitmq
